### ISSUE TITLE
这个springboot项目的user接口写的真心太垃圾了

### ISSUE THREAD

**Issue by mebest100** [xiaoyou-project/javaweb-xshop-back#1]
这个springboot项目的user接口写的真心太垃圾了。
查询用户不应该返回User对象吗？ 还特意getUserPassByUsername把密码单独查出来，真不知道你mybatis是怎么学的。
另外你看过登录接口的返回吗，username全是null,到了前端怎么做用户回显？
而且即便返回的User对象有信息，难道能把password也暴露出去吗，难道不应该单独封装一个UserDTO，通过beanutils.copyproperties拷贝User属性覆盖再返回UserDTO吗？

**Comment by xiaoyou66** [comment]
你好，感谢你反馈，首先这个项目只是自己的课设项目，写这个只是为了完成任务，当时没考虑太多
然后当时也是我们第一次接触web开发，没有开发经验，所以很多东西现在看来的确很垃圾
还有这个后端不是我负责的，负责这部分的同学当时也只是入门
其次，如果你有更好代码可以提交PR，我可以合并一下
最后，本项目本人不会进行维护，本人不对里面的代码负责。
